; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.3.6 on Fri Nov 26 2021 05:24:36 GMT+0000 (Coordinated Universal Time)
; Wait for set temperatures to be reached
M116 P0

